name: nodal
description: A central health management app for you and your family built using Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  code_assets: ^1.0.0
  collection: ^1.19.1
  daxle: ^1.1.0
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  hooks: ^1.0.1
  native_toolchain_c: ^0.17.4
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^20.1.1

flutter:
  uses-material-design: true
