name: nodal
description: A central health management app for you and your family built using Flutter.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  collection: ^1.19.1
  daxle: ^1.1.0
  flutter:
    sdk: flutter
  go_router: ^17.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
